print("Enter Robot Name: ")
robot_name = input()
print("Enter Robot Mass: ")
robot_mass = input()
print("Enter Wheel Radius: ")
wheel_radius = input()
print("Enter Motor RPM : ")
motor_rpm = input()
wheel_speed = (float(motor_rpm) * 2 * 3.14 * float(wheel_radius)) / 60
print("Robot:", robot_name)
print("Mass:", robot_mass, "kg")
print("Wheel radius:", wheel_radius, "m")
print("Motor RPM:", motor_rpm, "rpm")
print("Wheel speed:", round(wheel_speed,2), "m/s")